### ISSUE TITLE
callFunction requires params values to be of class R

### ISSUE THREAD

**Issue by Dima564** [yongjhih/RxParse#5]
```
public static <R> Observable<R> callFunction(String name, Map<String, R> params) 
```

**Comment by yongjhih** [comment]
Thanks for your feedback. I got that. It should be fixed next version.

https://github.com/yongjhih/RxParse/blob/a9a42a92c6555295bb2bd48c0ab1f1a261c9eff6/rxparse/src/main/java/rx/parse/ParseObservable.java#L137

The type of `params` shouldn't be `Map<String, R>` instead of `Map<String, ?>` such as the following line:

``` java
static <T> Observable<T> callFunction(String name, Map<String, ?> params)
```

ref. https://parse.com/docs/android/api/com/parse/ParseCloud.html

``` java
static <T> Task<T>  callFunctionInBackground(String name,
                        Map<String,?> params)
```

**Comment by yongjhih** [comment]
See also: 836c07e807ea6ccce34c466c1cbba666845c63b0
